# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runestone2017ObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'MobioSDKSwift', :git => 'https://gitbucket.mobio.vn/git/SDK_APP/ios_swift_lib.git', :branch => 'configForObjc'

end
